//! Generates the frozen Gateway registry from the validator-owned inventory.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

mod build_support;

use build_support::{Inventory, load_and_validate_registry};

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let inventory_path =
        manifest_dir.join("../../compat/upstream/inventories/gateway-protocol.json");
    println!("cargo:rerun-if-changed={}", inventory_path.display());
    println!("cargo:rerun-if-changed=build_support.rs");

    let inventory = load_and_validate_registry(&inventory_path)
        .unwrap_or_else(|error| panic!("frozen gateway registry validation failed: {error}"));

    let generated = generate_registry(&inventory);
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("gateway_registry.rs"), generated)
        .expect("write generated gateway registry");
}

fn generate_registry(inventory: &Inventory) -> String {
    let mut output =
        String::from("// @generated by build.rs from the validator-owned gateway-protocol.json.\n");
    writeln!(
        output,
        "pub(crate) const GENERATED_BASELINE_SHA: &str = {:?};",
        inventory.baseline_sha
    )
    .expect("write generated source");

    writeln!(
        output,
        "pub(crate) static GENERATED_CORE_METHODS: [CoreMethod; {}] = [",
        inventory.counts.methods
    )
    .expect("write generated source");
    for item in inventory.items.iter().filter(|item| item.kind == "method") {
        let scope = generated_scope(item.scope.as_deref().expect("validated method scope"));
        writeln!(
            output,
            "    CoreMethod::new({:?}, {scope}, {}),",
            item.id,
            item.advertised.expect("validated advertised flag")
        )
        .expect("write generated method");
    }
    output.push_str("];\n");

    writeln!(
        output,
        "pub(crate) static GENERATED_CORE_EVENTS: [CoreEvent; {}] = [",
        inventory.counts.events
    )
    .expect("write generated source");
    for item in inventory.items.iter().filter(|item| item.kind == "event") {
        writeln!(output, "    CoreEvent::new({:?}),", item.id).expect("write generated event");
    }
    output.push_str("];\n");

    writeln!(
        output,
        "pub(crate) static GENERATED_ROLES: [Role; {}] = [",
        inventory.counts.roles
    )
    .expect("write generated source");
    for item in inventory.items.iter().filter(|item| item.kind == "role") {
        let role = match (item.id.as_str(), item.protocol_class.as_deref()) {
            ("operator", Some("gateway")) => "Role::Operator",
            ("node", Some("gateway")) => "Role::Node",
            ("worker", Some("closed_worker")) => "Role::Worker",
            _ => panic!("unknown role inventory entry: {}", item.id),
        };
        writeln!(output, "    {role},").expect("write generated role");
    }
    output.push_str("];\n");

    writeln!(
        output,
        "pub(crate) static GENERATED_SCOPES: [OperatorScope; {}] = [",
        inventory.counts.scopes
    )
    .expect("write generated source");
    for item in inventory.items.iter().filter(|item| item.kind == "scope") {
        writeln!(
            output,
            "    {},",
            generated_operator_scope(item.id.as_str())
        )
        .expect("write generated scope");
    }
    output.push_str("];\n");
    output
}

fn generated_scope(scope: &str) -> &'static str {
    match scope {
        "operator.admin" => "MethodScope::Operator(OperatorScope::Admin)",
        "operator.read" => "MethodScope::Operator(OperatorScope::Read)",
        "operator.write" => "MethodScope::Operator(OperatorScope::Write)",
        "operator.approvals" => "MethodScope::Operator(OperatorScope::Approvals)",
        "operator.pairing" => "MethodScope::Operator(OperatorScope::Pairing)",
        "operator.talk.secrets" => "MethodScope::Operator(OperatorScope::TalkSecrets)",
        "node" => "MethodScope::Node",
        "dynamic" => "MethodScope::Dynamic",
        other => panic!("unknown method scope: {other}"),
    }
}

fn generated_operator_scope(scope: &str) -> &'static str {
    match scope {
        "operator.admin" => "OperatorScope::Admin",
        "operator.read" => "OperatorScope::Read",
        "operator.write" => "OperatorScope::Write",
        "operator.approvals" => "OperatorScope::Approvals",
        "operator.pairing" => "OperatorScope::Pairing",
        "operator.talk.secrets" => "OperatorScope::TalkSecrets",
        other => panic!("unknown operator scope: {other}"),
    }
}
