[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
]
confidence-threshold = 0.8
unused-allowed-license = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
