[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateSet('x64', 'arm64')]
    [string]$Architecture,

    [string]$OutputRoot,

    [switch]$SkipBuild,

    [string]$DesktopExecutable,

    [string]$CliExecutable,

    [string]$DaemonExecutable,

    [switch]$SkipMsix,

    [switch]$ReleaseMode
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

if ($ReleaseMode) {
    throw 'package.ps1 creates unsigned validation artifacts only. Release mode requires the separate sign.ps1 gate.'
}

$scriptRoot = Split-Path -Parent $PSCommandPath
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $scriptRoot '..\..'))
Import-Module (Join-Path $scriptRoot 'WindowsPackaging.psm1') -Force

$ownedRoot = [System.IO.Path]::GetFullPath((Join-Path $scriptRoot 'out'))
Assert-NoReparsePathComponents -Root $repoRoot -Path $ownedRoot
if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
    $OutputRoot = $ownedRoot
} else {
    $OutputRoot = [System.IO.Path]::GetFullPath($OutputRoot)
    if (-not $OutputRoot.Equals($ownedRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        Assert-ChildPath -Parent $ownedRoot -Child $OutputRoot | Out-Null
    }
}
[System.IO.Directory]::CreateDirectory($ownedRoot) | Out-Null
Assert-NoReparsePathComponents -Root $repoRoot -Path $ownedRoot
Assert-NoReparsePathComponents -Root $ownedRoot -Path $OutputRoot
[System.IO.Directory]::CreateDirectory($OutputRoot) | Out-Null
Assert-NoReparsePathComponents -Root $ownedRoot -Path $OutputRoot

$arch = Get-Architecture $Architecture
$version = Get-CanonicalVersion $repoRoot
$archRoot = Join-Path $OutputRoot $arch.Name
Remove-OwnedDirectory -OwnedRoot $OutputRoot -Path $archRoot
[System.IO.Directory]::CreateDirectory($archRoot) | Out-Null

$license = Join-Path $scriptRoot 'LICENSE.txt'
$assetSpec = Join-Path $scriptRoot 'assets\logo-spec.json'
$manifestTemplate = Join-Path $scriptRoot 'AppxManifest.template.xml'
$wixSource = Join-Path $scriptRoot 'wix\GtaClaw.wxs'
Assert-PlainFile $license | Out-Null
Assert-PlainFile $assetSpec | Out-Null
Assert-PlainFile $manifestTemplate | Out-Null
Test-WixSource $wixSource
Assert-HeadlessGraph $repoRoot

$workRoot = [System.IO.Path]::GetFullPath((Join-Path $scriptRoot '.work'))
Assert-NoReparsePathComponents -Root $scriptRoot -Path $workRoot
[System.IO.Directory]::CreateDirectory($workRoot) | Out-Null
Assert-NoReparsePathComponents -Root $scriptRoot -Path $workRoot
$buildRoot = Join-Path $workRoot "build\$($arch.RustTarget)"
if (-not $SkipBuild) {
    Remove-OwnedDirectory -OwnedRoot $workRoot -Path $buildRoot
    [System.IO.Directory]::CreateDirectory($buildRoot) | Out-Null
    Initialize-MsvcEnvironment $arch.Name | Out-Null
    $cargo = (Get-Command cargo -ErrorAction Stop).Source
    $priorTargetDir = $env:CARGO_TARGET_DIR
    try {
        $headlessTargetDir = Join-Path $buildRoot 'headless'
        $env:CARGO_TARGET_DIR = $headlessTargetDir
        Invoke-CheckedCommand -FilePath $cargo -Arguments @(
            'build',
            '--manifest-path', (Join-Path $repoRoot 'Cargo.toml'),
            '--locked',
            '--release',
            '--target', $arch.RustTarget,
            '--package', 'gta-claw-cli',
            '--package', 'gta-claw-daemon'
        )
        $desktopTargetDir = Join-Path $buildRoot 'desktop'
        $env:CARGO_TARGET_DIR = $desktopTargetDir
        Invoke-CheckedCommand -FilePath $cargo -Arguments @(
            'build',
            '--manifest-path', (Join-Path $repoRoot 'desktop\Cargo.toml'),
            '--locked',
            '--release',
            '--target', $arch.RustTarget,
            '--package', 'gta-claw-desktop'
        )
    } finally {
        $env:CARGO_TARGET_DIR = $priorTargetDir
    }
    $DesktopExecutable = Join-Path $buildRoot "desktop\$($arch.RustTarget)\release\gta-claw-desktop.exe"
    $CliExecutable = Join-Path $buildRoot "headless\$($arch.RustTarget)\release\gta-claw-cli.exe"
    $DaemonExecutable = Join-Path $buildRoot "headless\$($arch.RustTarget)\release\gta-claw-daemon.exe"
} elseif ([string]::IsNullOrWhiteSpace($DesktopExecutable) -or
    [string]::IsNullOrWhiteSpace($CliExecutable) -or
    [string]::IsNullOrWhiteSpace($DaemonExecutable)) {
    throw '-SkipBuild requires -DesktopExecutable, -CliExecutable, and -DaemonExecutable.'
}

$executables = @{
    Desktop = Assert-PlainFile $DesktopExecutable
    Cli = Assert-PlainFile $CliExecutable
    Daemon = Assert-PlainFile $DaemonExecutable
}
foreach ($path in $executables.Values) {
    Assert-PeArchitecture -Path $path -ExpectedMachine $arch.PeMachine
}

$nonReleaseText = @"
UNSIGNED NON-RELEASE VALIDATION ARTIFACT

This payload is generated by the P04b packaging prototype. It is not signed,
not trusted for deployment, and must not be published as a release.
"@

$layoutRoot = Join-Path $archRoot 'layouts'
$desktopPortable = Join-Path $layoutRoot 'portable-desktop'
$headlessPortable = Join-Path $layoutRoot 'portable-headless'
$msixLayout = Join-Path $layoutRoot 'msix'
$msiLayout = Join-Path $layoutRoot 'msi'
foreach ($directory in @($desktopPortable, $headlessPortable, $msixLayout, $msiLayout)) {
    [System.IO.Directory]::CreateDirectory($directory) | Out-Null
}

Copy-PlainFile -Source $executables.Desktop -Destination (Join-Path $desktopPortable 'gta-claw-desktop.exe')
Copy-PlainFile -Source $license -Destination (Join-Path $desktopPortable 'LICENSE.txt')
Write-Utf8File -Path (Join-Path $desktopPortable 'NON-RELEASE.txt') -Content $nonReleaseText
New-HashManifest $desktopPortable | Out-Null
Test-HashManifest $desktopPortable
Assert-PayloadSafety -Root $desktopPortable -ExpectedExecutables @('gta-claw-desktop.exe')

Copy-PlainFile -Source $executables.Cli -Destination (Join-Path $headlessPortable 'gta-claw-cli.exe')
Copy-PlainFile -Source $executables.Daemon -Destination (Join-Path $headlessPortable 'gta-claw-daemon.exe')
Copy-PlainFile -Source $license -Destination (Join-Path $headlessPortable 'LICENSE.txt')
Write-Utf8File -Path (Join-Path $headlessPortable 'NON-RELEASE.txt') -Content $nonReleaseText
New-HashManifest $headlessPortable | Out-Null
Test-HashManifest $headlessPortable
Assert-PayloadSafety -Root $headlessPortable -ExpectedExecutables @('gta-claw-cli.exe', 'gta-claw-daemon.exe')

$desktopZip = Join-Path $archRoot "gta-claw-desktop-$($version.Cargo)-windows-$($arch.Name)-portable-non-release.zip"
$headlessZip = Join-Path $archRoot "gta-claw-headless-$($version.Cargo)-windows-$($arch.Name)-portable-non-release.zip"
New-DeterministicZip -Root $desktopPortable -Destination $desktopZip | Out-Null
New-DeterministicZip -Root $headlessPortable -Destination $headlessZip | Out-Null
Write-ArtifactHash $desktopZip | Out-Null
Write-ArtifactHash $headlessZip | Out-Null

Copy-PlainFile -Source $executables.Desktop -Destination (Join-Path $msixLayout 'gta-claw-desktop.exe')
Copy-PlainFile -Source $license -Destination (Join-Path $msixLayout 'LICENSE.txt')
Write-Utf8File -Path (Join-Path $msixLayout 'NON-RELEASE.txt') -Content $nonReleaseText
$assetsDirectory = Join-Path $msixLayout 'Assets'
New-VisualAssets -SpecPath $assetSpec -OutputDirectory $assetsDirectory
New-AppxManifest `
    -TemplatePath $manifestTemplate `
    -OutputPath (Join-Path $msixLayout 'AppxManifest.xml') `
    -MsixVersion $version.Msix `
    -Architecture $arch.Msix
New-HashManifest $msixLayout | Out-Null
Test-HashManifest $msixLayout
Test-AppxManifest -Path (Join-Path $msixLayout 'AppxManifest.xml') -Version $version.Msix -Architecture $arch.Msix
Assert-PayloadSafety -Root $msixLayout -ExpectedExecutables @('gta-claw-desktop.exe')

Copy-PlainFile -Source $executables.Desktop -Destination (Join-Path $msiLayout 'gta-claw-desktop.exe')
Copy-PlainFile -Source $executables.Cli -Destination (Join-Path $msiLayout 'gta-claw-cli.exe')
Copy-PlainFile -Source $executables.Daemon -Destination (Join-Path $msiLayout 'gta-claw-daemon.exe')
Copy-PlainFile -Source $license -Destination (Join-Path $msiLayout 'LICENSE.txt')
Write-Utf8File -Path (Join-Path $msiLayout 'NON-RELEASE.txt') -Content $nonReleaseText
New-HashManifest $msiLayout | Out-Null
Test-HashManifest $msiLayout
Assert-PayloadSafety -Root $msiLayout -ExpectedExecutables @(
    'gta-claw-desktop.exe', 'gta-claw-cli.exe', 'gta-claw-daemon.exe'
)

$makeAppx = $null
$msixPackage = $null
if (-not $SkipMsix) {
    $makeAppx = Find-WindowsSdkTool 'makeappx.exe'
    $msixPackage = Join-Path $archRoot "gta-claw-desktop-$($version.Cargo)-windows-$($arch.Name)-unsigned.msix"
    Invoke-CheckedCommand -FilePath $makeAppx -Arguments @(
        'pack', '/h', 'SHA256', '/d', $msixLayout, '/p', $msixPackage, '/o'
    )
    $inspectionRoot = Join-Path $archRoot 'work\msix-inspection'
    [System.IO.Directory]::CreateDirectory((Split-Path -Parent $inspectionRoot)) | Out-Null
    Test-MsixPackage `
        -PackagePath $msixPackage `
        -MakeAppxPath $makeAppx `
        -InspectionRoot $inspectionRoot `
        -Version $version.Msix `
        -Architecture $arch.Msix
    Remove-OwnedDirectory -OwnedRoot $archRoot -Path (Join-Path $archRoot 'work')
    Write-ArtifactHash $msixPackage | Out-Null
}

$toolVersion = $null
if ($null -ne $makeAppx) {
    $toolVersion = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($makeAppx).FileVersion
}
$inventory = [ordered]@{
    schema = 1
    status = 'unsigned-non-release'
    cargo_version = $version.Cargo
    msix_version = $version.Msix
    msi_version = $version.Msi
    architecture = $arch.Name
    rust_target = $arch.RustTarget
    pe_machine = ('0x{0:X4}' -f $arch.PeMachine)
    package_identity = 'GTAStudio.GTAClaw'
    makeappx_version = $toolVersion
    artifacts = @(
        [System.IO.Path]::GetFileName($desktopZip),
        [System.IO.Path]::GetFileName($headlessZip)
    )
    deferred = @('signing', 'store-publication', 'app-installer-feed', 'msi-build', 'service-installation')
}
if ($null -ne $msixPackage) {
    $inventory.artifacts += [System.IO.Path]::GetFileName($msixPackage)
}
Write-Utf8File -Path (Join-Path $archRoot 'artifacts.json') -Content (($inventory | ConvertTo-Json -Depth 5) + "`n")

Write-Host "Created unsigned non-release Windows packaging outputs in '$archRoot'."
