//! Embeds the shipped bundled skill manifests at build time.
//!
//! The generated table is derived by walking `assets/bundled`, so the compiled
//! catalogue always reflects the tree that is actually shipped rather than a
//! list maintained by hand.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const MANIFEST_FILE_NAME: &str = "skill.json";

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let root = manifest_dir.join("assets/bundled");
    println!("cargo:rerun-if-changed={}", root.display());

    let directories = skill_directories(&root);
    assert!(
        !directories.is_empty(),
        "no bundled skill manifests found under {}",
        root.display()
    );

    let mut generated = String::from(
        "// @generated by build.rs from assets/bundled. Do not edit.\n\
         static EMBEDDED_BUNDLED_ASSETS: &[(&str, &str)] = &[\n",
    );
    for directory in &directories {
        let manifest = root.join(directory).join(MANIFEST_FILE_NAME);
        assert!(
            manifest.is_file(),
            "bundled skill directory {directory} carries no {MANIFEST_FILE_NAME}"
        );
        println!("cargo:rerun-if-changed={}", manifest.display());
        generated.push_str("    (\"");
        generated.push_str(directory);
        generated
            .push_str("\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/bundled/");
        generated.push_str(directory);
        generated.push('/');
        generated.push_str(MANIFEST_FILE_NAME);
        generated.push_str("\"))),\n");
    }
    generated.push_str("];\n");

    let output = PathBuf::from(env::var_os("OUT_DIR").expect("build output directory"))
        .join("bundled_assets.rs");
    fs::write(output, generated).expect("write generated bundled asset table");
}

fn skill_directories(root: &Path) -> Vec<String> {
    let mut directories = Vec::new();
    for entry in fs::read_dir(root).expect("read bundled skill root") {
        let entry = entry.expect("read bundled skill entry");
        let name = entry
            .file_name()
            .into_string()
            .expect("bundled skill directory name is UTF-8");
        assert!(
            entry.path().is_dir(),
            "unexpected non-directory entry {name} under {}",
            root.display()
        );
        assert!(
            !name.is_empty()
                && name.bytes().all(|byte| byte.is_ascii_lowercase()
                    || byte.is_ascii_digit()
                    || matches!(byte, b'-' | b'_')),
            "bundled skill directory name {name} leaves the frozen alphabet"
        );
        directories.push(name);
    }
    directories.sort();
    directories
}
