#Requires -Version 5.1
<#
.SYNOPSIS
    Regenerates crates/claw-plugin-api/src/registry_data.rs from the frozen
    upstream plugin inventory.

.DESCRIPTION
    compat/upstream/inventories/plugins.json is a frozen contract artifact and
    must never be edited. This script projects it into a committed Rust table so
    the registry is available without any runtime file access. The generated
    table is checked against the frozen inventory again at test time by
    crates/claw-plugin-api/tests/registry_matches_inventory.rs, so drift in
    either direction fails the build.

    The generator never invents an implementation status: every descriptor is
    emitted as `RegistrationOnly`. A plugin may only be promoted by editing the
    explicit override table in crates/claw-plugin-api/src/registry.rs.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$RepoRoot = Split-Path -Parent $PSScriptRoot
$InventoryPath = Join-Path $RepoRoot "compat\upstream\inventories\plugins.json"
$OutputPath = Join-Path $RepoRoot "crates\claw-plugin-api\src\registry_data.rs"

$inventory = Get-Content -LiteralPath $InventoryPath -Raw | ConvertFrom-Json
$items = @($inventory.items)
if ($items.Count -ne 137) {
    throw "expected 137 inventory rows, found $($items.Count)"
}

function Escape-RustString {
    param([string]$Value)
    return $Value.Replace("\", "\\").Replace('"', '\"')
}

$deliveryClassMap = @{
    "core"              = "DeliveryClass::Core"
    "official_external" = "DeliveryClass::OfficialExternal"
    "source_only_qa"    = "DeliveryClass::SourceOnlyQa"
}

$ordinalSorted = [System.Collections.Generic.List[object]]::new()
foreach ($item in $items) { [void]$ordinalSorted.Add($item) }
$comparison = [System.Comparison[object]] {
    param($left, $right)
    [StringComparer]::Ordinal.Compare([string]$left.id, [string]$right.id)
}
$ordinalSorted.Sort($comparison)
$sorted = $ordinalSorted.ToArray()

$builder = [System.Text.StringBuilder]::new()
$tick = [char]0x60
$baselineSha = [string]$inventory.baseline_sha
[void]$builder.AppendLine('//! Frozen upstream plugin inventory projected into Rust.')
[void]$builder.AppendLine('//!')
[void]$builder.AppendLine("//! Generated by ${tick}scripts/generate-plugin-registry.ps1${tick} from")
[void]$builder.AppendLine("//! ${tick}compat/upstream/inventories/plugins.json${tick} at baseline")
[void]$builder.AppendLine("//! ${tick}$baselineSha${tick}. Do not edit by hand: run the")
[void]$builder.AppendLine("//! generator instead. ${tick}tests/registry_matches_inventory.rs${tick} re-derives the")
[void]$builder.AppendLine('//! expected contents straight from the frozen JSON and fails on any drift.')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('use crate::registry::{DeliveryClass, InventoryRecord};')
[void]$builder.AppendLine('')
[void]$builder.AppendLine("/// Commit of ${tick}openclaw/openclaw${tick} the inventory was frozen at.")
[void]$builder.AppendLine("pub const BASELINE_SHA: &str = `"$baselineSha`";")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("/// Every plugin descriptor in the frozen upstream inventory, ordered by id.")
[void]$builder.AppendLine("pub(crate) static INVENTORY: [InventoryRecord; 137] = [")
foreach ($item in $sorted) {
    $delivery = $deliveryClassMap[[string]$item.delivery_class]
    if (-not $delivery) {
        throw "unknown delivery_class '$($item.delivery_class)' for '$($item.id)'"
    }
    [void]$builder.AppendLine("    InventoryRecord {")
    [void]$builder.AppendLine("        record_id: `"$(Escape-RustString ([string]$item.record_id))`",")
    [void]$builder.AppendLine("        id: `"$(Escape-RustString ([string]$item.id))`",")
    [void]$builder.AppendLine("        source_path: `"$(Escape-RustString ([string]$item.source_path))`",")
    [void]$builder.AppendLine("        package_name: `"$(Escape-RustString ([string]$item.package_name))`",")
    [void]$builder.AppendLine("        delivery_class: $delivery,")
    [void]$builder.AppendLine("    },")
}
[void]$builder.AppendLine("];")

$content = $builder.ToString() -replace "`r`n", "`n"
[System.IO.File]::WriteAllText($OutputPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Output "wrote $OutputPath ($($sorted.Count) descriptors)"
