//! End-to-end and mutation-based conformance harness tests.

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use claw_conformance::{
    ClaimLevel, ConformanceError, Contract, Evidence, FeatureClaim, ImplementationPointer,
    InventoryClaim, ParityStatus, Registry, ViolationCode, discover_claim_files, generate_report,
};

static NEXT_FIXTURE: AtomicU64 = AtomicU64::new(0);

struct Fixture {
    root: PathBuf,
}

impl Fixture {
    fn copy_upstream() -> Self {
        let root = std::env::temp_dir().join(format!(
            "claw-conformance-{}-{}",
            std::process::id(),
            NEXT_FIXTURE.fetch_add(1, Ordering::Relaxed)
        ));
        copy_directory(&upstream_root(), &root);
        install_fixture_workspace(&root, "claw-gateway", &[("protocol", "tests/protocol.rs")]);
        Self { root }
    }

    fn empty() -> Self {
        let root = std::env::temp_dir().join(format!(
            "claw-conformance-evidence-{}-{}",
            std::process::id(),
            NEXT_FIXTURE.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(&root).expect("create fixture");
        install_fixture_workspace(
            &root,
            "demo",
            &[
                ("protocol", "tests/protocol.rs"),
                ("single-file", "tests.rs"),
            ],
        );
        Self { root }
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        if self.root.exists() {
            fs::remove_dir_all(&self.root).expect("remove fixture");
        }
    }
}

fn upstream_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("compat")
        .join("upstream")
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

fn copy_directory(source: &Path, destination: &Path) {
    fs::create_dir_all(destination).expect("create destination");
    for entry in fs::read_dir(source).expect("read source") {
        let entry = entry.expect("read entry");
        let source_path = entry.path();
        let destination_path = destination.join(entry.file_name());
        if source_path.is_dir() {
            copy_directory(&source_path, &destination_path);
        } else {
            fs::copy(source_path, destination_path).expect("copy fixture file");
        }
    }
}

fn install_fixture_workspace(root: &Path, crate_name: &str, targets: &[(&str, &str)]) {
    let crate_root = root.join("crates").join(crate_name);
    fs::create_dir_all(crate_root.join("src")).expect("create fixture crate source");
    fs::write(
        root.join("Cargo.toml"),
        format!("[workspace]\nmembers = [\"crates/{crate_name}\"]\nresolver = \"3\"\n"),
    )
    .expect("write fixture workspace manifest");
    fs::write(
        root.join("Cargo.lock"),
        format!(
            "# This file is automatically @generated by Cargo.\n\
             # It is not intended for manual editing.\n\
             version = 4\n\n\
             [[package]]\n\
             name = \"{crate_name}\"\n\
             version = \"0.0.0\"\n"
        ),
    )
    .expect("write fixture lockfile");
    let test_targets = targets
        .iter()
        .map(|(name, path)| format!("\n[[test]]\nname = \"{name}\"\npath = \"{path}\"\n"))
        .collect::<String>();
    for (_, path) in targets {
        let target_path = crate_root.join(path);
        fs::create_dir_all(target_path.parent().expect("fixture target parent"))
            .expect("create fixture target parent");
        fs::write(target_path, "").expect("write fixture test target");
    }
    fs::write(
        crate_root.join("Cargo.toml"),
        format!(
            "[package]\n\
             name = \"{crate_name}\"\n\
             version = \"0.0.0\"\n\
             edition = \"2024\"\n\
             {test_targets}"
        ),
    )
    .expect("write fixture crate manifest");
    fs::write(crate_root.join("src").join("lib.rs"), "").expect("write fixture crate root");
}

fn install_test_package(root: &Path, directory: &str, package_name: &str, test_name: &str) {
    let package = root.join(directory);
    fs::create_dir_all(package.join("src")).expect("create package source");
    fs::write(
        package.join("Cargo.toml"),
        format!(
            "[package]\n\
             name = \"{package_name}\"\n\
             version = \"0.0.0\"\n\
             edition = \"2024\"\n"
        ),
    )
    .expect("write package manifest");
    fs::write(
        package.join("src").join("lib.rs"),
        format!("#[test]\nfn {test_name}() {{}}\n"),
    )
    .expect("write package test");
}

fn load_error(root: &Path) -> ConformanceError {
    Contract::load(root).expect_err("mutated contract must fail")
}

fn mutate_json(path: &Path, mutate: impl FnOnce(&mut serde_json::Value)) {
    let source = fs::read_to_string(path).expect("read JSON fixture");
    let mut value: serde_json::Value =
        serde_json::from_str(source.trim_start_matches('\u{feff}')).expect("parse JSON fixture");
    mutate(&mut value);
    fs::write(
        path,
        serde_json::to_vec_pretty(&value).expect("serialize JSON fixture"),
    )
    .expect("write JSON fixture");
}

fn enable_transition_policy(root: &Path, unimplemented: usize, partial: usize, implemented: usize) {
    let schema = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("transition-feature-ledger.schema.json");
    fs::copy(schema, root.join("feature-ledger.schema.json"))
        .expect("install transition schema fixture");
    mutate_json(&root.join("manifest.json"), |manifest| {
        let policy = &mut manifest["evidence_policy"];
        policy["allowed_statuses"] = serde_json::json!(["unimplemented", "partial", "implemented"]);
        policy["artifact_fields"] = serde_json::json!(["path", "test"]);
        policy["every_artifact_names_an_enabled_rust_test"] = serde_json::json!(true);
        policy["implementation_pointers_are_not_acceptance_evidence"] = serde_json::json!(true);
        policy["status_totals"] = serde_json::json!({
            "unimplemented": unimplemented,
            "partial": partial,
            "implemented": implemented
        });
    });
}

fn install_legacy_schema_and_policy(root: &Path) {
    let schema = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("legacy-feature-ledger.schema.json");
    fs::copy(schema, root.join("feature-ledger.schema.json"))
        .expect("install legacy schema fixture");
    mutate_json(&root.join("manifest.json"), |manifest| {
        let policy = manifest["evidence_policy"]
            .as_object_mut()
            .expect("evidence policy object");
        for field in [
            "allowed_statuses",
            "artifact_fields",
            "every_artifact_names_an_enabled_rust_test",
            "implementation_pointers_are_not_acceptance_evidence",
            "status_totals",
        ] {
            assert!(
                policy.remove(field).is_some(),
                "remove transition-only policy field {field}"
            );
        }
    });
}

#[test]
fn real_frozen_contract_loads_every_row() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    assert_eq!(
        contract.baseline_sha(),
        "b43e832fcc8000ed7287c7accc54e381db607f85"
    );
    assert_eq!(contract.ledgers().len(), 3);
    assert_eq!(
        contract
            .ledgers()
            .iter()
            .map(|ledger| (ledger.id(), ledger.features().len()))
            .collect::<Vec<_>>(),
        vec![
            ("gateway-core", 16),
            ("official-integration", 13),
            ("official-client-interop", 18),
        ]
    );
    assert_eq!(contract.inventories().len(), 10);
    assert_eq!(
        contract
            .inventories()
            .iter()
            .map(|(id, records)| (id.as_str(), records.len()))
            .collect::<Vec<_>>(),
        vec![
            ("channels", 29),
            ("clients", 10),
            ("config-domains", 47),
            ("gateway-protocol", 320),
            ("http-sse-endpoints", 18),
            ("migrations", 3),
            ("plugins", 137),
            ("providers", 78),
            ("release-deployment", 24),
            ("skills", 51),
        ]
    );
}

#[test]
fn canonical_count_drift_names_the_key_and_values() {
    let fixture = Fixture::copy_upstream();
    mutate_json(&fixture.root.join("manifest.json"), |manifest| {
        manifest["canonical_counts"]["artifact_json_files"] = serde_json::json!(17);
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::ManifestDrift);
    assert_eq!(error.subject(), Some("manifest.json"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "canonical count 'artifact_json_files' must be 18, got 17"
    );
}

#[test]
fn workspace_claim_manifests_pass_conformance() {
    let repository = repository_root();
    let contract =
        Contract::load(repository.join("compat").join("upstream")).expect("load frozen contract");
    let mut registry = Registry::new();
    let claim_files = discover_claim_files(&repository).expect("discover workspace claims");
    for claim_file in claim_files {
        registry
            .load_claims_file(claim_file)
            .expect("load workspace claims");
    }

    let report =
        generate_report(&contract, &registry, &repository).expect("validate workspace claims");
    assert_eq!(report.totals.total, 47);
    assert_eq!(
        report
            .inventories
            .iter()
            .map(|inventory| inventory.total)
            .sum::<usize>(),
        717
    );
}

#[test]
fn zero_registry_reports_the_honest_baseline() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let report =
        generate_report(&contract, &Registry::new(), repository_root()).expect("generate report");
    assert_eq!(report.totals.implemented, 0);
    assert_eq!(report.totals.partial, 0);
    assert_eq!(report.totals.unimplemented, 47);
    assert_eq!(report.totals.total, 47);
    assert_eq!(report.totals.registered, 0);
    assert_eq!(
        report
            .ledgers
            .iter()
            .flat_map(|ledger| ledger.features.iter())
            .map(|feature| feature.status)
            .collect::<Vec<_>>(),
        vec![ParityStatus::Unimplemented; 47]
    );
    assert_eq!(
        report
            .ledgers
            .iter()
            .flat_map(|ledger| ledger.features.iter())
            .filter(|feature| feature.registered)
            .count(),
        0
    );
    assert_eq!(
        report
            .inventories
            .iter()
            .map(|inventory| (
                inventory.inventory_id.as_str(),
                inventory.fully_implemented,
                inventory.registered,
                inventory.total,
            ))
            .collect::<Vec<_>>(),
        vec![
            ("channels", 0, 0, 29),
            ("clients", 0, 0, 10),
            ("config-domains", 0, 0, 47),
            ("gateway-protocol", 0, 0, 320),
            ("http-sse-endpoints", 0, 0, 18),
            ("migrations", 0, 0, 3),
            ("plugins", 0, 0, 137),
            ("providers", 0, 0, 78),
            ("release-deployment", 0, 0, 24),
            ("skills", 0, 0, 51),
        ]
    );
}

#[test]
fn fabricated_evidence_free_claim_is_rejected() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::new(
            "gateway.protocol.v4",
            ClaimLevel::Implemented,
            Vec::new(),
        ))
        .expect("register fabricated claim");
    let error = generate_report(&contract, &registry, repository_root())
        .expect_err("evidence-free claim must fail");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(error.message(), "claim has no recorded evidence");
}

#[test]
fn metadata_registration_never_inflates_implementation() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::registered("gateway.protocol.v4"))
        .expect("register feature metadata");
    registry
        .register_inventory(InventoryClaim::registered("providers", "provider:qianfan"))
        .expect("register inventory metadata");

    let report = generate_report(&contract, &registry, repository_root()).expect("generate report");
    assert_eq!(report.totals.implemented, 0);
    assert_eq!(report.totals.partial, 0);
    assert_eq!(report.totals.unimplemented, 47);
    assert_eq!(report.totals.registered, 1);
    let feature = report
        .ledgers
        .iter()
        .flat_map(|ledger| ledger.features.iter())
        .find(|feature| feature.feature_id == "gateway.protocol.v4")
        .expect("feature report");
    assert_eq!(feature.status, ParityStatus::Unimplemented);
    assert!(feature.registered);
    assert_eq!(feature.evidence_count, 0);
    let providers = report
        .inventories
        .iter()
        .find(|inventory| inventory.inventory_id == "providers")
        .expect("providers report");
    assert_eq!(providers.fully_implemented, 0);
    assert_eq!(providers.registered, 1);
    assert_eq!(providers.total, 78);
}

#[test]
fn claim_manifest_uses_structured_test_evidence_and_non_evidential_pointers() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let tests = fixture.root.join("crates").join("demo").join("tests");
    let source = fixture.root.join("crates").join("demo").join("src");
    fs::create_dir_all(&tests).expect("create claim test directory");
    fs::create_dir_all(&source).expect("create claim source directory");
    fs::write(
        tests.join("protocol.rs"),
        "#[test]\nfn proves_gateway_v4() {}\n",
    )
    .expect("write claim evidence");
    fs::write(source.join("protocol.rs"), "pub const VERSION: u8 = 4;\n")
        .expect("write claim implementation");
    let claims_path = fixture.root.join("conformance-claims.json");
    fs::write(
        &claims_path,
        serde_json::to_vec_pretty(&serde_json::json!({
            "schema_version": 1,
            "crate_name": "demo",
            "features": [{
                "feature_id": "gateway.protocol.v4",
                "level": "implemented",
                "evidence": [{
                    "path": "crates/demo/tests/protocol.rs",
                    "test": "proves_gateway_v4"
                }],
                "implementation_pointers": [{
                    "path": "crates/demo/src/protocol.rs",
                    "note": "Defines the implemented protocol version."
                }]
            }],
            "inventories": []
        }))
        .expect("serialize claims"),
    )
    .expect("write claims");

    let mut registry = Registry::new();
    registry
        .load_claims_file(&claims_path)
        .expect("load structured claims");
    let report =
        generate_report(&contract, &registry, &fixture.root).expect("validate structured claims");
    assert_eq!(report.totals.implemented, 1);
    assert_eq!(report.totals.partial, 0);
    assert_eq!(report.totals.unimplemented, 46);
}

#[test]
fn claim_manifest_rejects_legacy_test_name_field() {
    let fixture = Fixture::empty();
    let claims_path = fixture.root.join("conformance-claims.json");
    fs::write(
        &claims_path,
        serde_json::to_vec_pretty(&serde_json::json!({
            "schema_version": 1,
            "crate_name": "demo",
            "features": [{
                "feature_id": "gateway.protocol.v4",
                "level": "implemented",
                "evidence": [{
                    "path": "crates/demo/tests/protocol.rs",
                    "test_name": "proves_gateway_v4"
                }]
            }],
            "inventories": []
        }))
        .expect("serialize legacy claims"),
    )
    .expect("write legacy claims");

    let error = Registry::new()
        .load_claims_file(&claims_path)
        .expect_err("legacy test_name field must fail");
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(error.subject(), claims_path.to_str());
    assert_eq!(error.json_path(), Some("features[0].evidence[0].test_name"));
}

#[test]
fn implementation_pointer_cannot_replace_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let source = fixture.root.join("crates").join("demo").join("src");
    fs::create_dir_all(&source).expect("create pointer directory");
    fs::write(source.join("protocol.rs"), "pub const VERSION: u8 = 4;\n")
        .expect("write pointer target");
    let mut registry = Registry::new();
    registry
        .register_feature(
            FeatureClaim::implemented("gateway.protocol.v4", Vec::new())
                .with_implementation_pointers(vec![ImplementationPointer::new(
                    "crates/demo/src/protocol.rs",
                    "Defines the protocol version.",
                )]),
        )
        .expect("register pointer-only claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("pointer-only claim must fail");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(error.message(), "claim has no recorded evidence");
}

#[test]
fn evidence_path_resolution_is_ordinal_across_platforms() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let tests = fixture.root.join("crates").join("demo").join("tests");
    fs::create_dir_all(&tests).expect("create evidence directory");
    fs::write(tests.join("protocol.rs"), "#[test]\nfn proves_v4() {}\n").expect("write evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test("CRATES/demo/tests/protocol.rs", "proves_v4")],
        ))
        .expect("register case-aliased evidence");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("case-aliased path must fail ordinal resolution");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence file 'CRATES/demo/tests/protocol.rs' does not exist"
    );
}

#[test]
fn trailing_dot_alias_cannot_reach_self_referential_contract_data() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let compat = fixture.root.join("compat").join("upstream");
    fs::create_dir_all(&compat).expect("create compatibility directory");
    fs::write(compat.join("manifest.json"), "{}\n").expect("write compatibility file");
    let mut registry = Registry::new();
    registry
        .register_feature(
            FeatureClaim::registered("gateway.protocol.v4").with_implementation_pointers(vec![
                ImplementationPointer::new(
                    "compat./upstream/manifest.json",
                    "Attempted trailing-dot alias.",
                ),
            ]),
        )
        .expect("register trailing-dot pointer");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("trailing-dot alias must fail ordinal resolution");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "implementation pointer 'compat./upstream/manifest.json' does not exist"
    );
}

#[test]
fn fabricated_test_name_is_rejected() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates").join("demo").join("tests.rs");
    fs::create_dir_all(fixture.root.join("crates").join("demo")).expect("create evidence parent");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn real_test() { assert_eq!(2 + 2, 4); }\n",
    )
    .expect("write evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "fabricated_test")],
        ))
        .expect("register claim");
    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("fabricated test name must fail");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(
        error.message(),
        "evidence test 'fabricated_test' is not declared in 'crates/demo/tests.rs'"
    );
}

#[test]
fn orphan_source_file_cannot_supply_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("src")
        .join("orphan.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn forged_evidence_test() {}\n",
    )
    .expect("write orphan evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "forged_evidence_test")],
        ))
        .expect("register orphan claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("orphan source file must not count as evidence");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence path 'crates/demo/src/orphan.rs' is not reachable from a test-enabled Cargo target"
    );
}

#[test]
fn nested_reachable_module_can_supply_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let crate_root = fixture.root.join("crates").join("demo");
    fs::write(crate_root.join("src").join("lib.rs"), "mod security;\n")
        .expect("write fixture crate root");
    fs::write(
        crate_root.join("src").join("security.rs"),
        "mod nested {\n    mod proof;\n}\n",
    )
    .expect("write reachable outer module");
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("src")
        .join("security")
        .join("nested")
        .join("proof.rs");
    fs::create_dir_all(
        fixture
            .root
            .join(&evidence_path)
            .parent()
            .expect("evidence parent"),
    )
    .expect("create nested module directory");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn security_invariant_holds() {}\n",
    )
    .expect("write reachable evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "security_invariant_holds")],
        ))
        .expect("register reachable-module claim");

    let report = generate_report(&contract, &registry, &fixture.root)
        .expect("reachable module must count as evidence");
    assert_eq!(report.totals.implemented, 1);
    assert_eq!(report.totals.partial, 0);
    assert_eq!(report.totals.unimplemented, 46);
}

#[test]
fn path_attribute_module_can_supply_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let crate_root = fixture.root.join("crates").join("demo");
    fs::write(crate_root.join("src").join("lib.rs"), "mod outer;\n")
        .expect("write path-attributed module root");
    fs::write(
        crate_root.join("src").join("outer.rs"),
        "#[path = \"custom/proof.rs\"]\nmod proof;\n",
    )
    .expect("write path attribute in name.rs module");
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("src")
        .join("custom")
        .join("proof.rs");
    fs::create_dir_all(
        fixture
            .root
            .join(&evidence_path)
            .parent()
            .expect("evidence parent"),
    )
    .expect("create custom module directory");
    let decoy = crate_root
        .join("src")
        .join("outer")
        .join("custom")
        .join("proof.rs");
    fs::create_dir_all(decoy.parent().expect("decoy parent"))
        .expect("create path-attributed decoy directory");
    fs::write(decoy, "#[test]\nfn decoy_test() {}\n").expect("write path-attributed decoy");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn custom_module_runs() {}\n",
    )
    .expect("write path-attributed evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "custom_module_runs")],
        ))
        .expect("register path-attributed claim");

    let report = generate_report(&contract, &registry, &fixture.root)
        .expect("path-attributed module must count as evidence");
    assert_eq!(report.totals.implemented, 1);
    assert_eq!(report.totals.partial, 0);
    assert_eq!(report.totals.unimplemented, 46);
}

#[test]
fn macro_tokens_cannot_forge_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("tests")
        .join("protocol.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        "const _D: &str = stringify!({} #[test] fn forged_evidence_test() {});\n",
    )
    .expect("write macro-token forgery");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "forged_evidence_test")],
        ))
        .expect("register forged claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("macro tokens must not count as acceptance evidence");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence test 'forged_evidence_test' is not declared in \
         'crates/demo/tests/protocol.rs'"
    );
}

#[test]
fn unicode_macro_tokens_cannot_forge_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("tests")
        .join("protocol.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        concat!(
            "macro_rules! \u{5b8f} { ($($tokens:tt)*) => {}; }\n",
            "\u{5b8f}!(const _: () = (); #[test] fn forged_evidence_test() {});\n"
        ),
    )
    .expect("write Unicode macro-token forgery");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "forged_evidence_test")],
        ))
        .expect("register Unicode macro forged claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("Unicode macro tokens must not count as acceptance evidence");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence test 'forged_evidence_test' is not declared in \
         'crates/demo/tests/protocol.rs'"
    );
}

#[test]
fn malformed_macro_delimiters_cannot_forge_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("tests")
        .join("protocol.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        "m!([); #[test] fn forged_evidence_test() {}])\n",
    )
    .expect("write malformed macro forgery");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "forged_evidence_test")],
        ))
        .expect("register malformed forged claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("mismatched macro delimiters must fail closed");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence test 'forged_evidence_test' is not declared in \
         'crates/demo/tests/protocol.rs'"
    );
}

#[test]
fn cfg_key_value_cannot_forge_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("tests")
        .join("protocol.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[cfg(test = \"disabled\")]\n#[test]\nfn forged_evidence_test() {}\n",
    )
    .expect("write disabled cfg evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "forged_evidence_test")],
        ))
        .expect("register fabricated claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("disabled cfg test must not count as acceptance evidence");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence test 'forged_evidence_test' is not declared in \
         'crates/demo/tests/protocol.rs'"
    );
}

#[test]
fn exact_cfg_test_function_can_supply_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("tests")
        .join("protocol.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[cfg(test)]\n#[test]\nfn genuine_evidence_test() {}\n",
    )
    .expect("write cfg(test) evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "genuine_evidence_test")],
        ))
        .expect("register cfg(test) claim");

    let report = generate_report(&contract, &registry, &fixture.root)
        .expect("exact cfg(test) function must count as evidence");
    assert_eq!(report.totals.implemented, 1);
    assert_eq!(report.totals.partial, 0);
    assert_eq!(report.totals.unimplemented, 46);
}

#[test]
fn workspace_excluded_package_cannot_supply_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    fs::write(
        fixture.root.join("Cargo.toml"),
        "[workspace]\n\
         members = [\"crates/demo\"]\n\
         exclude = [\"vendored\"]\n\
         resolver = \"3\"\n",
    )
    .expect("exclude vendored package from workspace");
    install_test_package(
        &fixture.root,
        "vendored",
        "excluded-evidence",
        "excluded_package_test",
    );
    let evidence_path = Path::new("vendored").join("src").join("lib.rs");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "excluded_package_test")],
        ))
        .expect("register excluded-package claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("workspace-excluded packages must not supply acceptance evidence");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence path 'vendored/src/lib.rs' is not reachable from a test-enabled Cargo target"
    );
}

#[test]
fn workspace_unlisted_package_cannot_supply_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    install_test_package(
        &fixture.root,
        "crates/ghost",
        "unlisted-evidence",
        "unlisted_package_test",
    );
    let evidence_path = Path::new("crates").join("ghost").join("src").join("lib.rs");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "unlisted_package_test")],
        ))
        .expect("register unlisted-package claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("workspace-unlisted packages must not supply acceptance evidence");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence path 'crates/ghost/src/lib.rs' is not reachable from a test-enabled Cargo target"
    );
}

#[test]
fn cargo_target_disabled_for_testing_cannot_supply_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let crate_root = fixture.root.join("crates").join("demo");
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("src")
        .join("disabled.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn disabled_target_test() {}\nfn main() {}\n",
    )
    .expect("write disabled target");
    let manifest_path = crate_root.join("Cargo.toml");
    let manifest = fs::read_to_string(&manifest_path).expect("read fixture manifest");
    fs::write(
        manifest_path,
        format!(
            "{manifest}\n[[bin]]\nname = \"disabled\"\npath = \"src/disabled.rs\"\ntest = false\n"
        ),
    )
    .expect("disable target testing");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "disabled_target_test")],
        ))
        .expect("register disabled-target claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("test-disabled Cargo target must not count as evidence");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence path 'crates/demo/src/disabled.rs' is not reachable from a test-enabled Cargo target"
    );
}

#[test]
fn cargo_target_without_standard_harness_cannot_supply_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let crate_root = fixture.root.join("crates").join("demo");
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("tests")
        .join("harnessless.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn inert_harnessless_test() {}\nfn main() {}\n",
    )
    .expect("write harnessless target");
    let manifest_path = crate_root.join("Cargo.toml");
    let manifest = fs::read_to_string(&manifest_path).expect("read fixture manifest");
    fs::write(
        manifest_path,
        format!(
            "{manifest}\n[[test]]\nname = \"harnessless\"\npath = \"tests/harnessless.rs\"\nharness = false\n"
        ),
    )
    .expect("disable standard test harness");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "inert_harnessless_test")],
        ))
        .expect("register harnessless-target claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("harnessless Cargo target must not count as evidence");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence path 'crates/demo/tests/harnessless.rs' is not reachable from a test-enabled Cargo target"
    );
}

#[test]
fn cross_package_path_module_cannot_supply_acceptance_evidence() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    fs::write(
        fixture.root.join("Cargo.toml"),
        "[workspace]\nmembers = [\"crates/demo\", \"crates/decoy\"]\nresolver = \"3\"\n",
    )
    .expect("add decoy package to fixture workspace");
    let decoy_root = fixture.root.join("crates").join("decoy");
    fs::create_dir_all(decoy_root.join("src")).expect("create decoy package");
    fs::write(
        decoy_root.join("Cargo.toml"),
        "[package]\nname = \"decoy\"\nversion = \"0.0.0\"\nedition = \"2024\"\n",
    )
    .expect("write decoy manifest");
    fs::write(decoy_root.join("src").join("lib.rs"), "").expect("write decoy crate root");
    let evidence_path = Path::new("crates")
        .join("decoy")
        .join("src")
        .join("forged.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn cross_package_test() {}\n",
    )
    .expect("write cross-package evidence");
    fs::write(
        fixture
            .root
            .join("crates")
            .join("demo")
            .join("src")
            .join("lib.rs"),
        "#[path = \"../../decoy/src/forged.rs\"]\nmod forged;\n",
    )
    .expect("wire cross-package module");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "cross_package_test")],
        ))
        .expect("register cross-package claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("cross-package module must not count as evidence");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence path 'crates/decoy/src/forged.rs' is not reachable from a test-enabled Cargo target"
    );
}

#[test]
fn unreadable_path_attribute_cannot_bless_a_fallback_module() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let crate_root = fixture.root.join("crates").join("demo");
    fs::write(
        crate_root.join("src").join("lib.rs"),
        "#[path = b\"real.rs\"]\nmod forged;\n",
    )
    .expect("write invalid path attribute");
    let evidence_path = Path::new("crates")
        .join("demo")
        .join("src")
        .join("forged.rs");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn forged_fallback_test() {}\n",
    )
    .expect("write fallback decoy");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "forged_fallback_test")],
        ))
        .expect("register fallback claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("unreadable path attribute must suppress fallback resolution");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence path 'crates/demo/src/forged.rs' is not reachable from a test-enabled Cargo target"
    );
}

#[test]
fn fabricated_module_qualification_is_rejected() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates").join("demo").join("tests.rs");
    fs::create_dir_all(fixture.root.join("crates").join("demo")).expect("create evidence parent");
    fs::write(
        fixture.root.join(&evidence_path),
        "mod actual_module {\n    #[test]\n    fn real_test() {}\n}\n",
    )
    .expect("write qualified evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(
                &evidence_path,
                "fabricated_module::real_test",
            )],
        ))
        .expect("register qualified claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("fabricated module qualification must fail");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence test 'fabricated_module::real_test' is not declared in \
         'crates/demo/tests.rs'"
    );
}

#[test]
fn detached_test_attribute_does_not_bless_an_ordinary_function() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates").join("demo").join("tests.rs");
    fs::create_dir_all(fixture.root.join("crates").join("demo")).expect("create evidence parent");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn real_test() {}\nfn ordinary_function() {}\n",
    )
    .expect("write detached attribute evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "ordinary_function")],
        ))
        .expect("register ordinary function claim");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("ordinary function must not inherit a detached test attribute");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence test 'ordinary_function' is not declared in 'crates/demo/tests.rs'"
    );
}

#[cfg(unix)]
#[test]
fn symlinked_evidence_is_rejected_even_when_its_target_is_in_repository() {
    use std::os::unix::fs::symlink;

    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let legacy = fixture.root.join("src");
    let evidence = fixture.root.join("crates").join("demo").join("tests");
    fs::create_dir_all(&legacy).expect("create legacy directory");
    fs::create_dir_all(&evidence).expect("create evidence directory");
    fs::write(
        legacy.join("legacy.rs"),
        "#[test]\nfn forged_evidence() {}\n",
    )
    .expect("write forbidden target");
    symlink(
        fixture.root.join("src").join("legacy.rs"),
        evidence.join("proof.rs"),
    )
    .expect("create evidence symlink");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(
                "crates/demo/tests/proof.rs",
                "forged_evidence",
            )],
        ))
        .expect("register symlinked evidence");

    let error = generate_report(&contract, &registry, &fixture.root)
        .expect_err("symlinked evidence must fail");
    assert_eq!(error.code(), ViolationCode::ClaimEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence file 'crates/demo/tests/proof.rs' does not exist"
    );
}

#[test]
fn verified_feature_and_inventory_claims_are_counted() {
    let contract = Contract::load(upstream_root()).expect("load frozen contract");
    let fixture = Fixture::empty();
    let evidence_path = Path::new("crates").join("demo").join("tests.rs");
    fs::create_dir_all(fixture.root.join("crates").join("demo")).expect("create evidence parent");
    fs::write(
        fixture.root.join(&evidence_path),
        "#[test]\nfn proves_gateway_v4() { assert_eq!(4, 4); }\n\
         #[test]\nfn proves_qianfan() { assert_eq!(78, 78); }\n",
    )
    .expect("write evidence");
    let mut registry = Registry::new();
    registry
        .register_feature(FeatureClaim::implemented(
            "gateway.protocol.v4",
            vec![Evidence::test(&evidence_path, "proves_gateway_v4")],
        ))
        .expect("register feature");
    registry
        .register_inventory(InventoryClaim::implemented(
            "providers",
            "provider:qianfan",
            vec![Evidence::test(&evidence_path, "proves_qianfan")],
        ))
        .expect("register inventory");

    let report = generate_report(&contract, &registry, &fixture.root).expect("generate report");
    assert_eq!(report.totals.implemented, 1);
    assert_eq!(report.totals.partial, 0);
    assert_eq!(report.totals.unimplemented, 46);
    assert_eq!(report.totals.registered, 1);
    let providers = report
        .inventories
        .iter()
        .find(|inventory| inventory.inventory_id == "providers")
        .expect("providers report");
    assert_eq!(providers.fully_implemented, 1);
    assert_eq!(providers.registered, 1);
    assert_eq!(providers.total, 78);
}

#[test]
fn renamed_inventory_id_is_rejected_as_drift() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("inventories").join("providers.json");
    let source = fs::read_to_string(&path).expect("read providers");
    assert_eq!(source.matches("\"id\":  \"qianfan\"").count(), 1);
    fs::write(
        &path,
        source.replacen("\"id\":  \"qianfan\"", "\"id\":  \"renamed-qianfan\"", 1),
    )
    .expect("mutate providers");

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::InventoryDrift);
    assert_eq!(error.subject(), Some("providers"));
    assert_eq!(error.json_path(), None);
}

#[test]
fn raised_ledger_status_without_evidence_is_rejected() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    let source = fs::read_to_string(&path).expect("read ledger");
    assert_eq!(source.matches("\"status\":  \"unimplemented\"").count(), 16);
    fs::write(
        &path,
        source.replacen(
            "\"status\":  \"unimplemented\"",
            "\"status\":  \"implemented\"",
            1,
        ),
    )
    .expect("mutate ledger");

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "ledger status implemented requires recorded acceptance evidence"
    );
}

#[test]
fn legitimate_ledger_transitions_do_not_require_frozen_hashes() {
    let fixture = Fixture::copy_upstream();
    enable_transition_policy(&fixture.root, 45, 1, 1);
    let tests = fixture
        .root
        .join("crates")
        .join("claw-gateway")
        .join("tests");
    fs::create_dir_all(&tests).expect("create transitioned evidence directory");
    fs::write(
        tests.join("protocol.rs"),
        "#[test]\nfn negotiates_v4() {}\n#[test]\nfn accepts_node_v3() {}\n",
    )
    .expect("write transitioned evidence");
    let source = fixture.root.join("crates").join("claw-gateway").join("src");
    fs::create_dir_all(&source).expect("create implementation directory");
    fs::write(source.join("protocol.rs"), "pub const VERSION: u8 = 4;\n")
        .expect("write implementation pointer");
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        let features = ledger["features"].as_array_mut().expect("features array");
        features[0]["status"] = serde_json::json!("partial");
        features[0]["acceptance_evidence"]["status"] = serde_json::json!("partial");
        features[0]["acceptance_evidence"]["artifacts"] = serde_json::json!([{
            "path": "crates/claw-gateway/tests/protocol.rs",
            "test": "negotiates_v4"
        }]);
        features[0]["known_differences"] =
            serde_json::json!(["General client rejection remains incomplete."]);
        features[0]["implementation_pointers"] = serde_json::json!([{
            "path": "crates/claw-gateway/src/protocol.rs",
            "note": "Defines the Rust protocol version."
        }]);
        features[1]["status"] = serde_json::json!("implemented");
        features[1]["acceptance_evidence"]["status"] = serde_json::json!("accepted");
        features[1]["acceptance_evidence"]["artifacts"] = serde_json::json!([{
            "path": "crates/claw-gateway/tests/protocol.rs",
            "test": "accepts_node_v3"
        }]);
        features[1]["known_differences"] = serde_json::json!(["No known differences."]);
    });
    let validator = fixture.root.join("validate.ps1");
    let mut validator_source = fs::read_to_string(&validator).expect("read validator");
    validator_source.push_str("\n# Transition command fixture\n");
    fs::write(validator, validator_source).expect("write validator fixture");

    let contract = Contract::load(&fixture.root).expect("load transitioned ledger");
    assert_eq!(contract.ledgers()[0].id(), "gateway-core");
    assert_eq!(contract.ledgers()[0].features().len(), 16);
    assert_eq!(
        contract.ledgers()[0].features()[0].id(),
        "gateway.protocol.v4"
    );
    assert_eq!(
        contract.ledgers()[0].features()[1].id(),
        "gateway.protocol.node-v3-window"
    );
}

#[test]
fn legacy_schema_cannot_authorize_a_ledger_transition() {
    let fixture = Fixture::copy_upstream();
    install_legacy_schema_and_policy(&fixture.root);
    let tests = fixture
        .root
        .join("crates")
        .join("claw-gateway")
        .join("tests");
    fs::create_dir_all(&tests).expect("create legacy evidence directory");
    fs::write(
        tests.join("protocol.rs"),
        "#[test]\nfn negotiates_v4() {}\n",
    )
    .expect("write legacy evidence");
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["artifacts"] = serde_json::json!([{
            "path": "crates/claw-gateway/tests/protocol.rs",
            "test": "negotiates_v4"
        }]);
        ledger["features"][0]["known_differences"] =
            serde_json::json!(["Gateway negotiation remains incomplete."]);
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerDrift);
    assert_eq!(error.subject(), Some("ledgers"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "legacy feature schema does not permit ledger status transitions"
    );
}

#[test]
fn transition_manifest_policy_and_status_totals_are_accepted() {
    let fixture = Fixture::copy_upstream();
    enable_transition_policy(&fixture.root, 47, 0, 0);

    let contract = Contract::load(&fixture.root).expect("load transition manifest");
    assert_eq!(contract.ledgers().len(), 3);
    assert_eq!(
        contract
            .ledgers()
            .iter()
            .map(|ledger| ledger.features().len())
            .sum::<usize>(),
        47
    );
}

#[test]
fn transition_manifest_status_totals_must_match_ledgers() {
    let fixture = Fixture::copy_upstream();
    enable_transition_policy(&fixture.root, 46, 1, 0);

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::ManifestDrift);
    assert_eq!(error.subject(), Some("manifest.json"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "manifest status_totals do not match mutable ledger rows"
    );
}

#[test]
fn ledger_artifact_must_name_an_enabled_rust_test() {
    let fixture = Fixture::copy_upstream();
    let tests = fixture
        .root
        .join("crates")
        .join("claw-gateway")
        .join("tests");
    fs::create_dir_all(&tests).expect("create ledger evidence directory");
    fs::write(
        tests.join("protocol.rs"),
        "#[test]\nfn real_gateway_test() {}\n",
    )
    .expect("write ledger evidence");
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["artifacts"] = serde_json::json!([{
            "path": "crates/claw-gateway/tests/protocol.rs",
            "test": "fabricated_gateway_test"
        }]);
        ledger["features"][0]["known_differences"] =
            serde_json::json!(["Gateway negotiation remains incomplete."]);
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence test 'fabricated_gateway_test' is not declared in \
         'crates/claw-gateway/tests/protocol.rs'"
    );
}

#[test]
fn duplicate_feature_id_across_ledgers_is_rejected() {
    let fixture = Fixture::copy_upstream();
    let path = fixture
        .root
        .join("ledgers")
        .join("official-integration.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["feature_id"] = serde_json::json!("gateway.protocol.v4");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerDrift);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(error.message(), "duplicate feature ID across ledgers");
}

#[test]
fn feature_classification_must_match_its_ledger() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["classification"] = serde_json::json!("official_integration");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerDrift);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "feature classification official_integration does not match ledger classification gateway_core"
    );
}

#[test]
fn feature_last_verified_sha_must_match_the_baseline() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["last_verified_sha"] =
            serde_json::json!("0000000000000000000000000000000000000000");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerDrift);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "last_verified_sha must equal b43e832fcc8000ed7287c7accc54e381db607f85"
    );
}

#[test]
fn unknown_ledger_status_is_rejected_at_its_json_path() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["status"] = serde_json::json!("blocked");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(error.subject(), Some("ledgers/gateway-core.json"));
    assert_eq!(error.json_path(), Some("features[0].status"));
}

#[test]
fn blank_ledger_evidence_artifact_is_rejected() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["artifacts"] = serde_json::json!([{
            "path": " ",
            "test": "negotiates_v4"
        }]);
        ledger["features"][0]["known_differences"] =
            serde_json::json!(["Negotiation remains incomplete."]);
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "evidence path ' ' must be a repository-relative forward-slash path"
    );
}

#[test]
fn partial_ledger_status_requires_partial_evidence_state() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["status"] = serde_json::json!("accepted");
        ledger["features"][0]["acceptance_evidence"]["artifacts"] = serde_json::json!([{
            "path": "crates/claw-gateway/tests/protocol.rs",
            "test": "negotiates_v4"
        }]);
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "partial ledger status requires partial evidence"
    );
}

#[test]
fn blank_ledger_evidence_requirement_is_rejected() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["artifacts"] = serde_json::json!([{
            "path": "crates/claw-gateway/tests/protocol.rs",
            "test": "negotiates_v4"
        }]);
        ledger["features"][0]["acceptance_evidence"]["required"] = serde_json::json!(" ");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "acceptance evidence requirement must not be blank"
    );
}

#[test]
fn unimplemented_ledger_status_rejects_populated_evidence() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["acceptance_evidence"]["status"] = serde_json::json!("partial");
        ledger["features"][0]["acceptance_evidence"]["artifacts"] = serde_json::json!([{
            "path": "crates/claw-gateway/tests/protocol.rs",
            "test": "negotiates_v4"
        }]);
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::LedgerEvidence);
    assert_eq!(error.subject(), Some("gateway.protocol.v4"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "unimplemented ledger status requires missing acceptance evidence"
    );
}

#[test]
fn mutable_ledger_rows_still_obey_the_frozen_schema() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["title"] = serde_json::json!("");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(error.subject(), Some("ledgers/gateway-core.json"));
    assert_eq!(error.json_path(), Some("features[0].title"));
    assert_eq!(error.message(), "title must not be empty");
}

#[test]
fn windows_path_is_not_accepted_as_an_official_uri() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["upstream_source"]["official_url"] =
            serde_json::json!("C:\\not-a-uri");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(error.subject(), Some("ledgers/gateway-core.json"));
    assert_eq!(
        error.json_path(),
        Some("features[0].upstream_source.official_url")
    );
    assert_eq!(error.message(), "official_url must be an absolute URI");
}

#[test]
fn forward_slash_windows_path_is_not_accepted_as_an_official_uri() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["upstream_source"]["official_url"] =
            serde_json::json!("C:/not-a-uri");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(
        error.json_path(),
        Some("features[0].upstream_source.official_url")
    );
    assert_eq!(error.message(), "official_url must be an absolute URI");
}

#[test]
fn malformed_percent_escape_is_not_accepted_as_an_official_uri() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["upstream_source"]["official_url"] =
            serde_json::json!("https://docs.openclaw.ai/invalid%2");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(
        error.json_path(),
        Some("features[0].upstream_source.official_url")
    );
    assert_eq!(error.message(), "official_url must be an absolute URI");
}

#[test]
fn non_ascii_official_uri_is_rejected() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["upstream_source"]["official_url"] =
            serde_json::json!("https://docs.openclaw.ai/\u{00a0}");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(
        error.json_path(),
        Some("features[0].upstream_source.official_url")
    );
    assert_eq!(error.message(), "official_url must be an absolute URI");
}

#[test]
fn explicit_null_is_not_accepted_as_an_official_uri() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["upstream_source"]["official_url"] = serde_json::Value::Null;
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(error.subject(), Some("ledgers/gateway-core.json"));
    assert_eq!(
        error.json_path(),
        Some("features[0].upstream_source.official_url")
    );
}

#[test]
fn whitespace_padded_official_uri_is_rejected() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    mutate_json(&path, |ledger| {
        ledger["features"][0]["upstream_source"]["official_url"] =
            serde_json::json!(" https://docs.openclaw.ai/gateway ");
    });

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(error.subject(), Some("ledgers/gateway-core.json"));
    assert_eq!(
        error.json_path(),
        Some("features[0].upstream_source.official_url")
    );
    assert_eq!(error.message(), "official_url must be an absolute URI");
}

#[test]
fn trailing_json_content_is_rejected() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    let mut source = fs::read_to_string(&path).expect("read ledger");
    source.push_str("\n{}\n");
    fs::write(path, source).expect("append trailing JSON");

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(error.subject(), Some("ledgers/gateway-core.json"));
    assert_eq!(error.json_path(), Some("$"));
    assert_eq!(error.message(), "trailing content after the JSON document");
}

#[test]
fn baseline_artifact_retains_an_independent_frozen_hash() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("baseline.json");
    let mut source = fs::read_to_string(&path).expect("read baseline");
    source.push('\n');
    fs::write(path, source).expect("mutate baseline");

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::ManifestDrift);
    assert_eq!(error.subject(), Some("baseline.json"));
    assert_eq!(error.json_path(), None);
    assert_eq!(
        error.message(),
        "frozen support artifact changed in baseline.json; expected SHA-256 \
         02bdfca9e47ace25ffd99199f2efc8dd04b80f0c4b35c8a63b08700dd9846dea, found \
         9af9feea2b1dc352420fe63b05325cb50ee7b2159a22d217a9647fb1e3b1ae74"
    );
}

#[test]
fn malformed_ledger_reports_the_precise_json_path() {
    let fixture = Fixture::copy_upstream();
    let path = fixture.root.join("ledgers").join("gateway-core.json");
    let source = fs::read_to_string(&path).expect("read ledger");
    assert_eq!(source.matches("\"tier\":  \"tier_1\"").count(), 16);
    fs::write(
        &path,
        source.replacen("\"tier\":  \"tier_1\"", "\"tier\":  \"tier_9\"", 1),
    )
    .expect("mutate ledger");

    let error = load_error(&fixture.root);
    assert_eq!(error.code(), ViolationCode::JsonSchema);
    assert_eq!(error.subject(), Some("ledgers/gateway-core.json"));
    assert_eq!(error.json_path(), Some("features[0].tier"));
}
